config/routes.rb
Rails.application.routes.draw do
root :to => 'users#new'
resources :users
post "oauth/callback" => "oauths#callback"
get "oauth/callback" => "oauths#callback"
get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                    :bigint           not null, primary key
#  activated             :boolean
#  avatar                :string
#  crypted_password      :string
#  email                 :string
#  introduce             :text
#  name                  :integer
#  nickname              :string
#  password              :string
#  password_confirmation :string
#  role                  :integer
#  salt                  :string
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :authentications, :dependent => :destroy
  accepts_nested_attributes_for :authentications
  validates :email, uniqueness: true
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  # 下記はログイン機能を実装した後、コメントアウト
  # before_action :check_admin
  before_action :set_admin_user, only: %i[show destroy]

  def index
    @general_users = User.general
    @admin_users = User.admin
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(admin_user_params)

    if @user.save
      redirect_to admin_users_path, notice: "管理者ユーザー「#{@user.nickname}」が作成されました。"
    else
      render :new
    end
  end

  def show
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path, notice: "管理者ユーザー「#{@user.nickname}」が削除されました。"
  end

  private

  def set_admin_user
    @user = User.find(params[:id])
  end

  # ログイン機能を実装次第コメントアウト
  # def check_admin
    # 現在のユーザーが管理者ユーザーかチェック
    # redirect_to root_path unless current_user.admin?
  # end

  def admin_user_params
    params.require(:user).permit(:nickname, :email).merge(role: :admin)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/oauths_controller.rb
class OauthsController < ApplicationController
  skip_before_action :require_login, raise: false
  def oauth
    login_at(params[:provider])
  end

  def callback
    provider = params[:provider]
    if @user = login_from(provider)
      redirect_to root_path, :notice => "Logged in from #{provider.titleize}!"
    else
      begin
        @user = create_from(provider)
        # NOTE: this is the place to add '@user.activate!' if you are using user_activation submodule

        reset_session # protect from session fixation attack
        auto_login(@user)
        redirect_to root_path, :notice => "Logged in from #{provider.titleize}!"
      rescue
        redirect_to root_path, :alert => "Failed to login from #{provider.titleize}!"
      end
    end
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = login(params[:email], params[:password])


    if @user
      redirect_back_or_to(new_user_path, notice: 'ログインに成功しました')
    else
      flash.now[:alert] = 'ログインに失敗しました'
      render :new
    end
  end
  end

  def destroy
      logout
    redirect_to(login_path, notice: 'ログアウトしました')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create], raise: false

  def oauth
    login_at(params[:provider])
  end

  def new
    @user = User.new
  end
        
  def callback
    provider = params[:provider]
    if @user = login_from(provider)
      redirect_to root_path, :notice => "Logged in from #{provider.titleize}!"
    else
      begin
        @user = create_from(provider)
        # NOTE: this is the place to add '@user.activate!' if you are using user_activation submodule

        reset_session # protect from session fixation attack
        auto_login(@user)
        redirect_to root_path, :notice => "Logged in from #{provider.titleize}!"
      rescue
        redirect_to root_path, :alert => "Failed to login from #{provider.titleize}!"
      end
    end
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
      flash[:notice] = 'ユーザーの作成に成功しました'
    else
      flash.now[:alert] = 'ユーザーの作成に失敗しました'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to root_path, notice: 'ユーザー情報を変更しました。'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/index.html.slim
- if flash.notice.present?
  div.bg-green-100.border.text-green-700.px-4.py-3.rounded.relative
    = notice

h1 管理者ユーザー

table.table-auto
  thead
    tr
      th.px-4.py-2 ユーザー
      th.px-4.py-2
  - @admin_users.each do |user|
    tbody
      tr
        td.border.px-4.py-2
          = link_to  user.nickname, admin_user_path(user)
        td.border.px-4.py-2
          = link_to '削除', admin_user_path(user), method: :delete, data: {confirm: "削除しますか？"}

h1 一般ユーザー

table.table-auto
  thead
    tr
      th.px-4.py-2 ユーザー
      th.px-4.py-2
  - @general_users.each do |user|
    tbody
      tr
        td.border.px-4.py-2
          = link_to  user.nickname, admin_user_path(user)
        td.border.px-4.py-2
          = link_to '削除', admin_user_path(user), method: :delete, data: {confirm: "削除しますか？"}

button.bg-blue-500.hover:bg-blue-700.text-white.font-bold.py-2.px-4.rounded-full.mt-2
  = link_to '管理者作成', new_admin_user_path

app/views/admin/users/new.html.slim
h1 管理ユーザー作成

= form_with model: [:admin, @user], local: true do |f|
  div
    = f.label :nickname, class: 'block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2'
    = f.text_field :nickname, class: 'appearance-none block w-full bg-white text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500'
  div
    = f.label :email, class: 'block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2'
    = f.email_field :email, class: 'appearance-none block w-full bg-white text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500'

  = f.submit '登録する', class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full mt-2'

app/views/admin/users/show.html.slim
table.table-auto.mt-2
  tbody
    tr
      th.border ユーザー名
      td.border.px-4.py-2
        = @user.nickname
    tr
      th.border メールアドレス
      td.border.px-4.py-2
        = @user.email
    tr
      th.border 自己紹介
      td.border.px-4.py-2
        = @user.introduce

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | App
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
  body
    = render 'shared/header'
    main.container.mx-auto.px-8
      = yield

app/views/oauths/callback.html.slim
h1 Oauths#callback
p Find me in app/views/oauths/callback.html.slim

app/views/oauths/oauth.html.slim
h1 Oauths#oauth
p Find me in app/views/oauths/oauth.html.slim

app/views/shared/_header.html.slim
h1 AppName
nav
  - if logged_in?
    = link_to 'ログアウト', logout_path, method: :delete
  - else
    = link_to 'ログイン', login_path

app/views/user_sessions/create.html.slim
h1 UserSessions#create
p Find me in app/views/user_sessions/create.html.slim

app/views/user_sessions/destroy.html.slim
h1 UserSessions#destroy
p Find me in app/views/user_sessions/destroy.html.slim

app/views/user_sessions/new.html.slim
h1 UserSessions#new
p Find me in app/views/user_sessions/new.html.slim

= form_with url: login_path, method: :post do |f|
  = f.label :email
  = f.text_field :email
  = f.label :password
  = f.password_field :password
  = f.submit 'ログイン'

app/views/users/create.html.slim
h1 Users#create
p Find me in app/views/users/create.html.slim

app/views/users/edit.html.slim
h1 Users#edit
p Find me in app/views/users/edit.html.slim

= form_with model: @user do |f|
  = render 'shared/error_messages', object: f.object
  = render 'form', form: f
  = f.submit t('.submit'), class: 'btn btn-primary'

app/views/users/new.html.slim
h1 新規会員登録

= form_with model: @user, local: true do |f|
  = f.label :email
  = f.text_field :email
  = f.label :password
  = f.password_field :password
  = f.label :password_confirmation
  = f.password_field :password_confirmation
  = f.submit "登録"
br
br
  = link_to 'lineでログインする', auth_at_provider_path(:provider => :line) 

app/views/users/update.html.slim
h1 Users#update
p Find me in app/views/users/update.html.slim